# Generated by Django 5.2.5 on 2026-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitereview',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
