# Generated by Django 5.2.5 on 2026-01-23 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_sitereview_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerNotification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('system', 'System Message'), ('profile', 'Profile Update'), ('security', 'Security Alert'), ('payment', 'Payment Update'), ('job', 'Job Update')], default='system', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employer.employer')),
            ],
            options={
                'db_table': 'employer_notification_table',
                'ordering': ['-created_at'],
            },
        ),
    ]
