# Generated by Django 5.2.5 on 2026-01-26 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitereview',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_reviews', to='employer.employer'),
        ),
    ]
