# Generated by Django 4.2 on 2026-01-19 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_self', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmSetting',
            fields=[
                ('setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_frequency', models.CharField(choices=[('realtime', 'Real-time (Continuous)'), ('hourly', 'Hourly'), ('daily', 'Daily (at 00:00 UTC)')], default='realtime', max_length=20)),
                ('data_retention', models.CharField(choices=[('30', '30 days'), ('90', '90 days'), ('180', '180 days'), ('365', '1 year'), ('indefinite', 'Indefinitely')], default='90', max_length=20)),
                ('export_csv', models.BooleanField(default=True)),
                ('export_json', models.BooleanField(default=False)),
                ('export_parquet', models.BooleanField(default=False)),
                ('storage_used_mb', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'algorithm_setting_table',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('xgboost', 'XGBoost'), ('random_forest', 'Random Forest'), ('neural_network', 'Neural Network'), ('logistic_regression', 'Logistic Regression'), ('prophet', 'Prophet')], default='xgboost', max_length=20)),
                ('model_category', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('clustering', 'Clustering'), ('time_series', 'Time Series'), ('recommendation', 'Recommendation')], default='classification', max_length=20)),
                ('algorithm', models.CharField(default='XGBoost', max_length=50)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('accuracy', models.FloatField(default=0.0)),
                ('dataset_size', models.IntegerField(default=0)),
                ('training_time_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('training', 'Training'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_trained_at', models.DateTimeField(blank=True, null=True)),
                ('features_used', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ml_model_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataset_size', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('training_time_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('training', 'Training'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('log_file', models.FileField(blank=True, null=True, upload_to='training_logs/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='admin_self.mlmodel')),
            ],
            options={
                'db_table': 'training_history_table',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='DataFeature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('categorical', 'Categorical'), ('date', 'Date'), ('timestamp', 'Timestamp'), ('text', 'Text')], default='float', max_length=20)),
                ('category', models.CharField(choices=[('user', 'User Data'), ('booking', 'Booking Data'), ('financial', 'Financial Data'), ('review', 'Review Data'), ('location', 'Location Data')], default='user', max_length=20)),
                ('sample_values', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('models_using', models.ManyToManyField(blank=True, related_name='features', to='admin_self.mlmodel')),
            ],
            options={
                'db_table': 'data_feature_table',
                'ordering': ['category', 'name'],
            },
        ),
    ]
