# Generated by Django 4.2 on 2026-01-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
        ('admin_self', '0002_algorithmsetting_mlmodel_traininghistory_datafeature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlgorithmSetting',
        ),
        migrations.RemoveField(
            model_name='traininghistory',
            name='model',
        ),
        migrations.AlterField(
            model_name='commission',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.0001, max_digits=5),
        ),
        migrations.AlterField(
            model_name='payout',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='payout',
            name='payout_method',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('razorpay', 'Razorpay')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformrevenue',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.DeleteModel(
            name='DataFeature',
        ),
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.DeleteModel(
            name='TrainingHistory',
        ),
    ]
