# Generated by Django 4.2 on 2026-01-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_self', '0003_delete_algorithmsetting_remove_traininghistory_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.001, max_digits=5),
        ),
    ]
